// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYWuWkA236oIr9q37Yyo51Mug8zVnYmVU',
    appId: '1:60014275602:web:dc89468e3a139d405abccb',
    messagingSenderId: '60014275602',
    projectId: 'keidot-15545',
    authDomain: 'keidot-15545.firebaseapp.com',
    storageBucket: 'keidot-15545.firebasestorage.app',
    measurementId: 'G-XNGE25547X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoFAEKOqXPZ8lpIxfVa_CQnRrmJdg8T2E',
    appId: '1:60014275602:android:658460ef1c41c3a15abccb',
    messagingSenderId: '60014275602',
    projectId: 'keidot-15545',
    storageBucket: 'keidot-15545.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArOsntEqv47z8jYPZ34QP7891yoTCCDyk',
    appId: '1:60014275602:ios:0a1b64d2d67785125abccb',
    messagingSenderId: '60014275602',
    projectId: 'keidot-15545',
    storageBucket: 'keidot-15545.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArOsntEqv47z8jYPZ34QP7891yoTCCDyk',
    appId: '1:60014275602:ios:0a1b64d2d67785125abccb',
    messagingSenderId: '60014275602',
    projectId: 'keidot-15545',
    storageBucket: 'keidot-15545.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYWuWkA236oIr9q37Yyo51Mug8zVnYmVU',
    appId: '1:60014275602:web:f6b2fdecce4d2b0c5abccb',
    messagingSenderId: '60014275602',
    projectId: 'keidot-15545',
    authDomain: 'keidot-15545.firebaseapp.com',
    storageBucket: 'keidot-15545.firebasestorage.app',
    measurementId: 'G-RGTVF6G206',
  );
}
